# -*- coding: utf-8 -*-
"""assignment7theoretrical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4stPBg6sZMlyBnGR90tnTZ2LF8hosfG
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
from scipy.stats import norm
from scipy.stats import binom
import math
from scipy import stats

prob_box1= 1/2
prob_box2= 1/2
prob_box1_red=1/3
prob_box1_green=2/3
prob_box2_red=2/3
prob_box2_green=1/3
x1=np.arange(0,2)
x2=[i+0.25 for i in x1]
h1=[prob_box1_red,prob_box1_green]
h2=[prob_box2_red,prob_box2_green]
plt.bar(x1, h1, color = "blue", width = 0.25, label = "box1")
plt.bar(x2, h2, color = "green", width = 0.25, label = "box2")
plt.xlabel('Cases')
plt.ylabel('Probabilities')
plt.xticks(x1  + 0.25/2,["red ball", "green ball"])
plt.title("Probability of drawing balls")
plt.legend()
plt.show()

#P(A)=P(A/B)P(B)+P(A/C)P(C)
#Here event A:drawing red ball
# event B:drawing red ball from box1
# event c:drawing red ball from box1
#P(B/A)=(P(A/B)*P(B))/P(A)

prob_box1_select=prob_box1*prob_box1_red/(prob_box1*prob_box1_red+prob_box2*prob_box2_red)
prob_box2_select=prob_box2*prob_box2_red/(prob_box1*prob_box1_red+prob_box2*prob_box2_red)
print(f'probability that box 1 is selected=',prob_req)