# -*- coding: utf-8 -*-
"""assignment7simulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/133LNzBFa7FFbvG_XOco4DgsXF6Sjtcwr
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
num_sim=10000000
#from theoretrical python code
prob_box1_select=1/3
prob_box2_select=2/3
data_box = bernoulli.rvs(size=num_sim,p=0.5)

count_red1=0
count_red=0
data_box1_red = bernoulli.rvs(size=num_sim,p=1/3)
data_box2_red = bernoulli.rvs(size=num_sim,p=2/3)
for i in range(num_sim):
   if data_box[i] == 1 and data_box1_red[i] == 1 :
      count_red += 1
      count_red1 += 1
   elif data_box[i] == 0 and data_box2_red[i] == 1 :
      count_red += 1  
prob_box1=count_red1/count_red
print(f'(simulation)probability box1 is selected is ',prob_box1)
prob_box2=1-prob_box1
x1=np.arange(0,2)
x2=[i+0.25 for i in x1]
h1=[prob_box1,prob_box2]
h2=[prob_box1_select,prob_box2_select]
plt.bar(x1, h1, color = "blue", width = 0.25, label = "simulation")
plt.bar(x2, h2, color = "green", width = 0.25, label = "theoretrical")
plt.xlabel('Cases')
plt.ylabel('Probabilities')
plt.xticks(x1  + 0.25/2,["box1", "box2"])
plt.title("Probability of selected boxes")
plt.legend()
plt.show()